#
# Module manifest for module 'PSCopyFileEx'
#
# Generated by: LordBubbles
#
# Generated on: 17/01/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSCopyFileEx.psm1'

# Version number of this module.
ModuleVersion = '1.0.3'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '8937842e-0d66-46a9-b6ef-19367593d244'

# Author of this module
Author = 'LordBubbles'

# Copyright statement for this module
Copyright = '(c) 2025 LordBubbles. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A PowerShell module for copying files with advanced progress reporting and Windows API support. Features include detailed progress bars, speed reporting, and support for both managed and Windows API file copy operations.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Copy-FileEx'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'PSCopyFileEx.psm1',
    'Public\Copy-FileEx.ps1',
    'LICENSE',
    'README.md',
    'en-US\about_PSCopyFileEx.help.txt'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'file-copy','windows-api','progress','file-transfer','copy','powershell','CopyFileEx', 'copy-item'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/LordBubblesDev/PSCopyFileEx'

        #ReadmeUri of this module
        ReadmeUri = 'https://github.com/LordBubblesDev/PSCopyFileEx/blob/main/README.md'

        # License of the module
        LicenseUri = 'https://github.com/LordBubblesDev/PSCopyFileEx/blob/main/LICENSE'

        # Add documentation property
        PackageReadmeFile = 'README.md'

        # Set licence acceptance requirement
        PackageRequireLicenseAcceptance = $false

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
1.0.3:
- Readjusted verbose logging logic

1.0.2:
- Fixed verbose messages showing success messages when the operation failed
- Fixed verbose messages indicating which copy method is used once per file copied
- Fixed files being overwritten without -Force parameter when the file names include wildcards
- Fixed cancellation with CTRL+C not working in all cases

1.0.1:
- Fixed Include/Exclude filter handling for recursive directory operations
- Improved CTRL+C cancellation handling for both API and managed copy methods
- Fixed file handle cleanup and proper stream disposal
- Added immediate stream closure on cancellation
- Added proper cleanup of partial files when cancelled
- Fixed progress reporting to not show success messages when cancelled
- Added debug logging for troubleshooting
- Fixed file locking issues during cancellation
- Improved error handling and reporting
- Added proper garbage collection during cleanup

1.0.0 - Initial release with support for:
- Advanced progress reporting with speed calculations
- Windows API support through CopyFileEx
- Managed file copy fallback
- Support for single files and directories
- Recursive copy support
- Force parameter for overwrite control
'@

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/LordBubblesDev/PSCopyFileEx/blob/main/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

